title: "ShpeeBot Docs"

# Use Just The Docs remote theme by pmarsciell
remote_theme: pmarsceill/just-the-docs

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: "light"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "ShpeeBot on GitHub":
    - "//github.com/LeoDoesThings/ShpeeBot"

# Makes Aux links open in a new tab.
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2020 LeoDT. Licensed under the <a href=\"https://github.com/ShpeeBot/docs/tree/master/LICENSE.txt\">BSD-3-Clause.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
